-- 043: challenge descriptions become markdown (Session 56).
--
-- Until now functions/api/challenges.js stored a server-sanitized HTML subset:
-- only <a href> survived, newlines became <br>, everything else was entity-escaped.
-- Every user-written field is markdown now, rendered (and sanitized) by
-- js/markdown.js, so these rows are converted: <a href="X">T</a> -> [T](X),
-- <br> -> newline, entities unescaped. Generated from production on 2026-10-10.
-- Each UPDATE matches the exact old text, so re-running it, or running it after
-- a row has changed, is a no-op.

UPDATE challenges SET description = 'Formalize and codify the ideas in Frank Chimero''s classic essay about wildlife management protocols, [Only Openings.](https://frankchimero.com/blog/2014/only-openings/)'
 WHERE id = 1 AND description = 'Formalize and codify the ideas in Frank Chimero''s classic essay about wildlife management protocols, <a href="https://frankchimero.com/blog/2014/only-openings/" target="_blank" rel="noopener noreferrer">Only Openings.</a>';

UPDATE challenges SET description = 'Turn the [Kafka Index](https://protocolized.io/resources/the-kafka-index/) proposed by Nadia Asparouvhova into a rigorous instrument in the form of a quiz and/or agentic AI inventory, that protocol stewards can use to assess the badness of their protocols.'
 WHERE id = 2 AND description = 'Turn the <a href="https://protocolized.io/resources/the-kafka-index/" target="_blank" rel="noopener noreferrer">Kafka Index</a> proposed by Nadia Asparouvhova into a rigorous instrument in the form of a quiz and/or agentic AI inventory, that protocol stewards can use to assess the badness of their protocols.';

UPDATE challenges SET description = 'Mine the [Protocol Supercut video](https://www.youtube.com/watch?v=HiUcxUC9Z2c) compiled by Kara Kittel by using AI to identify, date, and classify the scenes included, extract insights, and use it to develop a historical analysis of the portrayal of protocols in movies.'
 WHERE id = 3 AND description = 'Mine the <a href="https://www.youtube.com/watch?v=HiUcxUC9Z2c" target="_blank" rel="noopener noreferrer">Protocol Supercut video</a> compiled by Kara Kittel by using AI to identify, date, and classify the scenes included, extract insights, and use it to develop a historical analysis of the portrayal of protocols in movies.';

UPDATE challenges SET description = 'Turn the classic [xkcd Dependency cartoon](https://xkcd.com/2347/) into an interesting meme generator, perhaps using image AI to do more than just change the caption and labels.'
 WHERE id = 4 AND description = 'Turn the classic <a href="https://xkcd.com/2347/" target="_blank" rel="noopener noreferrer">xkcd Dependency cartoon</a> into an interesting meme generator, perhaps using image AI to do more than just change the caption and labels.';

UPDATE challenges SET description = 'Protocols for dose timing [can improve](https://www.biorxiv.org/content/10.1101/2025.09.11.675645v1) oncological treatment outcomes independent of total dosage amounts. Tumors can have concave or convex dose response curves, which partially determines how quickly or slowly tumors develop resistance when on consistent, increasing, decreasing or randomized dosing schedules. How do these early results compare to dose response curves in ecological settings, such as the application of herbicides to soybean crops, wildlife population management programs, or safety improvement initiatives in mail delivery services?'
 WHERE id = 7 AND description = 'Protocols for dose timing <a href="https://www.biorxiv.org/content/10.1101/2025.09.11.675645v1" target="_blank" rel="noopener noreferrer">can improve</a> oncological treatment outcomes independent of total dosage amounts. Tumors can have concave or convex dose response curves, which partially determines how quickly or slowly tumors develop resistance when on consistent, increasing, decreasing or randomized dosing schedules. How do these early results compare to dose response curves in ecological settings, such as the application of herbicides to soybean crops, wildlife population management programs, or safety improvement initiatives in mail delivery services?';

UPDATE challenges SET description = 'Create a timeline illustrating where the word "protocol" emerged, how it evolved, forked, and died out in various instances. The end of the timeline should indicate and briefly explain the main ways the word is in use this decade.'
 WHERE id = 8 AND description = 'Create a timeline illustrating where the word &quot;protocol&quot; emerged, how it evolved, forked, and died out in various instances. The end of the timeline should indicate and briefly explain the main ways the word is in use this decade.';

UPDATE challenges SET description = 'Permitting systems bundle multiple incommensurable purposes — safety review, environmental compliance, democratic notification, political discretion, rent protection, revenue generation — that are often genuinely in tension. But orthogonal to these purpose conflicts is a second problem: the cognitive and administrative burden imposed by coordination complexity itself. Each additional touchpoint, form, portal, and institutional handoff imposes load on applicants and administrators alike, independent of whether the underlying purposes conflict. 

The challenge: design a methodology to separate purpose-conflict friction from coordination-complexity friction in a real permit corpus. If the two are separable, it opens a tractable intervention space — agentic approaches that absorb coordination costs without requiring anyone to relinquish purposes they actually care about, and without the political economy of consolidation. The interesting result is not that permitting can be made simpler, but that its irreducible complexity can be made to fall on machines rather than people.'
 WHERE id = 10 AND description = 'Permitting systems bundle multiple incommensurable purposes — safety review, environmental compliance, democratic notification, political discretion, rent protection, revenue generation — that are often genuinely in tension. But orthogonal to these purpose conflicts is a second problem: the cognitive and administrative burden imposed by coordination complexity itself. Each additional touchpoint, form, portal, and institutional handoff imposes load on applicants and administrators alike, independent of whether the underlying purposes conflict. <br><br>The challenge: design a methodology to separate purpose-conflict friction from coordination-complexity friction in a real permit corpus. If the two are separable, it opens a tractable intervention space — agentic approaches that absorb coordination costs without requiring anyone to relinquish purposes they actually care about, and without the political economy of consolidation. The interesting result is not that permitting can be made simpler, but that its irreducible complexity can be made to fall on machines rather than people.';
